### ISSUE TITLE
Incompatibility with Throughout the Ages (crashes, game fails to dispose)

### ISSUE THREAD

**Issue by Zireael07** [Terasology/Minimap#6] opened 2016-05-28 12:00 UTC
null pointer exception
##

**Comment by Cervator** [comment] 2016-05-28 18:31
Hi @Zireael07 - could you please post the full error message?

Oddly, it works fine for me - Omega 462 with Core + Minimap, nothing else. Did you have any other modules enabled?

I'm sorry I missed you on IRC but saw your comments in the log later. I wonder if something on your system is causing more than just performance issues? Sounds like you've got a laptop (the Radeon 6630M mention) which often encounter graphic issues not normally seen on desktops.

**Comment by Zireael07** [comment] 2016-05-29 08:20
I tried to use the minimap with Throughtout the Ages, as it's supposed to be 'the most complete experience'. Maybe they don't mesh with each other? Although I'd expect the minimap/HUD code to be module-independent...

No graphic issues, just CPU spikes regardless of dev/stable and/or modules loaded, and yes it's a laptop.

**Comment by Cervator** [comment] 2016-05-30 04:30
Alright, as expected I can confirm this - although it may be more of a TTA issue or overall issue related to world generation and imaging the results. I suspect we can link this to https://github.com/MovingBlocks/Terasology/issues/1524 as similar crashes occur when you try to preview a TTA map.

I'll rename this issue and leave it around till we figure out TTA to where we're actually sure it is implemented correctly as per latest architecture. Then likely Minimap for it will work well again.

Maybe there would be something we could consider to harden this module against such crashes. We did similar stuff for map previewing in the past.

Maybe worth noting that the crash didn't dispose the game and the high CPU usage is indicative of the chunk generator threads still running. One maybe similar example would be https://github.com/MovingBlocks/Terasology/issues/1775 along with https://github.com/MovingBlocks/Terasology/issues/1296 for general relevance.

**Comment by jdrueckert** [comment] 2020-09-29 20:21
@skaldarnar @Cervator as TTA is more or less dead and will probably only be plundered for things to take out into other or new modules, should we close this?

**Comment by Cervator** [comment] 2020-09-30 02:29
IMHO I don't _think_ so - whatever TTA did to crash Minimap is (probably?) still a live bug. Minimap should be hardened against that whether we have any modules actively trying to crash it or not :-)

Being that it has been so long, however, it could have been accidentally fixed in the meantime. Might be hard to even figure out since TTA itself likely doesn't run anymore 🤔 

So with that in mind it may make sense to close this anyway letting the odds decide whether it gets seen and fixed at some point in the future or just disappears under the march of time.

**Closed by Cervator** 2020-09-30 02:29 UTC
